### ISSUE TITLE
Create a login page

### ISSUE THREAD

**Issue by benmelz** [CS320S22T3/taskbox#10]
Create a login page component for the client. For now, we are looking for something atomic and the absolute bare minimum for an integrated login feature.

That means I'm limiting this purely to a single HTML `<form>` with:
- An email field
- A password field
- A login button

In addition that means no CSS for now.

From an architectural standpoint, the component should be self contained. It should accept some function prop such as `onSubmit` that will be called with the `email` and `password` inputs when the form is submitted.

Reference material:
- [react forms](https://reactjs.org/docs/forms.html)

**Comment by benmelz** [comment]
With respect to the `onSubmit` modular behavior we're looking for:

This is a code snippet from the linked react form documentation

```
class NameForm extends React.Component {
  constructor(props) {
    super(props);
    this.state = {value: ''};

    this.handleChange = this.handleChange.bind(this);
    this.handleSubmit = this.handleSubmit.bind(this);
  }

  handleChange(event) {
    this.setState({value: event.target.value});
  }

  handleSubmit(event) {
    alert('A name was submitted: ' + this.state.value);
    event.preventDefault();
  }

  render() {
    return (
      <form onSubmit={this.handleSubmit}>
        <label>
          Name:
          <input type="text" value={this.state.value} onChange={this.handleChange} />
        </label>
        <input type="submit" value="Submit" />
      </form>
    );
  }
}
```

Your component's implementation of `handleSubmit` should do something like:

```
  ...
  handleSubmit(event) {
    ...
    this.props.onSubmit(this.state.email, this.state.password);
  }
  ...
```

**Comment by Fish7793** [comment]
We have created a file called "LoginForm.tsx" and have implemented it as suggested above.

**Comment by benmelz** [comment]
Great! If you think it's ready to be merged, now would be the time to open a PR for that branch. Once you do that I'll assign another group to review it for you guys.
