### ISSUE TITLE
Create navbar component

### ISSUE THREAD

**Issue by benmelz** [CS320S22T3/taskbox#17]
As in #10, we want something barebones that should live in `client/components/Navbar.tsx`. The component should just render a `<nav>` containing a single "logout" button. No CSS for now.

**Comment by rohitankit** [comment]
I pushed the navbar branch to the repo, I think it's ready for review, Thanks.

**Comment by benmelz** [comment]
Cool, you can put it up for review by opening a PR for it - if there's not a button to do so on the home page, there should be one [here](https://github.com/CS320S22T3/taskbox/branches).
