### ISSUE TITLE
Organization and structure

### ISSUE THREAD

**Issue by benmelz** [CS320S22T3/taskbox#32]
Things are okay for now in development, but eventually it would be a good idea to merge `client/package.json` and `server/package.json` (as well as all the nested configuration files and `src` directories).

If we want to eventually deploy the application, we'll need a more centralized setup.

**Comment by daniel-melanson** [comment]
I disagree with this change. Obviously, you have more experience so you can correct me if I'm missing something. But each app,  client or server, has it own set of dependencies and scripts. Merging the scripts wouldn't be impossible, but I am more concerned about dependency conflicts. Server needs package X at version Y, client needs package X at version Z.

I feel like deployment should still be possible with the current setup. Something similar to this?

- Checkout entire repository.
- `cd client`
- `npm run build`
- Copy built website into `/var/http/` on some vps with apache set up.
- `cd ../server`
- `npm start`

**Comment by benmelz** [comment]
> I disagree with this change. Obviously, you have more experience so you can correct me if I'm missing something. But each app,  client or server, has it own set of dependencies and scripts. Merging the scripts wouldn't be impossible, but I am more concerned about dependency conflicts. Server needs package X at version Y, client needs package X at version Z.
> 
> 
> 
> I feel like deployment should still be possible with the current setup. Something similar to this?
> 
> 
> 
> - Checkout entire repository.
> 
> - `cd client`
> 
> - `npm run build`
> 
> - Copy built website into `/var/http/` on some vps with apache set up.
> 
> - `cd ../server`
> 
> - `npm start`

Fair points - my main counterarguments would have more to do with "the ideal development situation" vs. "our development situation". But, we can discuss more next meeting in person as this isn't too pressing.
