### ISSUE TITLE
Add `GET /api/users/:id/tasks` endpoint

### ISSUE THREAD

**Issue by benmelz** [CS320S22T3/taskbox#64]
Should live in `/server/src/routes/users.route.ts`.

The endpoint should return all tasks  that the user is involved with, either as an assigner or assignee (all columns, and all supplemental columns from subtables) that the user is involved with.

Modeling the route file after [`sessions.route.ts`](https://github.com/CS320S22T3/taskbox/blob/034794534cfc36e3579ab5d0bb49af172add6788/server/src/routes/sessions.route.ts#L1) and given a router named `users`, the endpoint in question should look something like:

```
users.get("/:id/tasks", (req: Request, res: Response) => {
  ...
});
```

More info will be provided after the database tables have been created.

**Comment by daniel-melanson** [comment]
Does this need to be protected in any way? Should we only select tasks that also include the currently authed user?

**Comment by benmelz** [comment]
> Does this need to be protected in any way? Should we only select tasks that also include the currently authed user?

Yeah probably - I figured I wouldn't require it per-se as we can add that later pretty easily. I think it's up to the assignee if they want to include it.
