### ISSUE TITLE
Add `PUT /api/tasks/:id` endpoint

### ISSUE THREAD

**Issue by benmelz** [CS320S22T3/taskbox#66]
Should live in `/server/src/routes/tasks.route.ts`.

The endpoint should update an existing task as well as its supplemental subtable record (time off request, performance review, etc) using attributes from the request body. Be sure that the body attributes are validated using `express-validator`.

Modeling the route file after [`sessions.route.ts`](https://github.com/CS320S22T3/taskbox/blob/034794534cfc36e3579ab5d0bb49af172add6788/server/src/routes/sessions.route.ts#L49) and given a router named `tasks`, the endpoint in question should look something like:

```
tasks.put(
  "/:id",
  validate(...),
  async (req: Request, res: Response) => {
    // attempt to update the record and respond accordingly
  }
);
```

More info will be provided after the database tables have been created.

**Comment by benmelz** [comment]
In addition, make sure that the response includes the server's result of the update request (the updated attributes as JSON).

For example a successful response should have a body like:
```
{
  id: "6",
  assigner_id: "2",
  ...
}
```

**Comment by sselkef** [comment]
What would a body for a requested change look like? Would it include only a task id and the attributes it wants to update or all of the attributes for tasks?
