### ISSUE TITLE
Create `users` database table

### ISSUE THREAD

**Issue by benmelz** [CS320S22T3/taskbox#8]
Create a database table for user storage named `users`. This will involve setting up `seqelize` and setting up a `User` model.

The table should have three columns with (types)
- `id` (primary key)
- `email` (citext)
- `password_digest` (string, length 60)

The idea here is to create the absolute minimum for a login system. Other columns and relationships can be added later.

Seeds for at least one development user should also be included. Something like `employee@development.com` + `password`

Reference material:
- [dotenv](https://github.com/motdotla/dotenv#readme)
- [sequelize getting started](https://sequelize.org/master/manual/getting-started.html)
- [sequelize migrations](https://sequelize.org/v6/manual/migrations.html)
- [sequelize + express guide](https://stackabuse.com/using-sequelize-orm-with-nodejs-and-express/)

**Comment by daniel-melanson** [comment]
You will need to change the authentication system.

Currently, there is a environment variable `SQL_CONNECTION_URI` with the necessary fields.

Ben would like us to use https://sequelize.org/master/manual/migrations.html instead.

Not sure how that would look; sorry. Good luck.

**Comment by benmelz** [comment]
Going off what @daniel-melanson is referencing, you'll have to refactor some of the configuration via `dotenv` I would take a look at the library documentation, as well as the current [loading system](https://github.com/CS320S22T3/taskbox/blob/81672eba9a8f5d4e7d0b21c1e770dc35aaa30fa8/server/src/constants.ts#L16) in place.

**Comment by daniel-melanson** [comment]
Could you also update the [README](https://github.com/CS320S22T3/taskbox/blob/main/README.md) as necessary?

**Comment by benmelz** [comment]
> Could you also update the [README](https://github.com/CS320S22T3/taskbox/blob/main/README.md) as necessary?

As a sidenote I actually planned on maintaining the README as we go so I'll be on top of that.
